# Generated by Django 6.0.6 on 2026-07-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_upgrade_fee', models.DecimalField(decimal_places=2, default=200.0, help_text='VIP Upgrade fee in USDT', max_digits=20)),
                ('company_wallet_address', models.CharField(default='0x71C7656EC7ab88b098defB751B7401B5f6d8976F', help_text='Default company USDT wallet address', max_length=255)),
                ('wallet_network', models.CharField(default='ERC20', help_text='Network for company wallet (e.g. ERC20, TRC20, BEP20)', max_length=50)),
                ('conversion_fee_percent', models.DecimalField(decimal_places=2, default=1.0, help_text='Conversion fee percentage (e.g., 1.00 for 1%)', max_digits=5)),
                ('enable_currency_converter', models.BooleanField(default=True, help_text='Enable or disable currency conversion on dashboard')),
                ('enable_vip_upgrade', models.BooleanField(default=True, help_text='Enable or disable VIP upgrade submissions')),
                ('enable_withdrawals', models.BooleanField(default=True, help_text='Enable or disable withdrawal requests')),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
