# Generated by Django 6.0.6 on 2026-07-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_adminwalletaddress_remove_wallet_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(default='Company USDT Wallet', max_length=100)),
                ('wallet_address', models.CharField(max_length=255)),
                ('network', models.CharField(default='ERC20', help_text='e.g., ERC20, TRC20, BEP20', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
