# Generated by Django 6.0.6 on 2026-07-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('INVESTMENT', 'Investment'), ('PROFIT', 'Profit'), ('REFERRAL_BONUS', 'Referral Bonus'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('CURRENCY_CONVERSION', 'Currency Conversion'), ('FEE', 'Fee')], max_length=20),
        ),
    ]
