# Generated by Django 4.2.30 on 2026-07-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_ticketmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='support_images/'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='support_images/'),
        ),
    ]
